services:
  recruitment_platform:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_USER: ${JWT_SECRET_USER}
      JWT_SECRET_ADMIN: ${JWT_SECRET_ADMIN}
      JWT_SECRET_SUPERADMIN: ${JWT_SECRET_SUPERADMIN}
      ZEPTOMAIL_USER: ${ZEPTOMAIL_USER}
      ZEPTOMAIL_PASS: ${ZEPTOMAIL_PASS}
      NODE_ENV: ${NODE_ENV:-production}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      PORT: 8080
    restart: unless-stopped
