version: "3.8"
services:
  recruitment_platform:
    build:
      context: ./recruitment-platform-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL_RECRUITMENT}
      JWT_SECRET_USER: ${JWT_SECRET_USER_RECRUITMENT}
      JWT_SECRET_ADMIN: ${JWT_SECRET_ADMIN_RECRUITMENT}
      JWT_SECRET_SUPERADMIN: ${JWT_SECRET_SUPERADMIN_RECRUITMENT}
      ZEPTOMAIL_BOUNCE_ADDRESS: ${ZEPTOMAIL_BOUNCE_ADDRESS_RECRUITMENT}
      ZEPTOMAIL_TOKEN: ${ZEPTOMAIL_TOKEN_RECRUITMENT}
      NODE_ENV: ${NODE_ENV:-production}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      PORT: 8080
    restart: unless-stopped
